### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by aryanbhasin** [aryanbhasin/tiger-eats#10]
- [ ] Add implementation for 'Rate' feature
- [ ] Add cuisine tags to all places and fix tag functionality
- [ ] Add unique images for each eatery

     - Decide whether to use locally hosted images or online. If online, need to optimise loading

- [ ] Decide whether to use native Firebase or web SDK, then implement Firebase for:
     - [ ] Converting links on 'More' to Firebase
     - [ ] All the places' data also? JSON pulled from Firebase?
- [ ] Add 'Featured' boolean for a place using Firebase
- [ ] Redesign Place Info page to make it cleaner
- [ ] Decide whether to add notifications feature or not (#1)
- [ ] Add local eateries' info (Princeton-based)
